name: allpay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_route: ^7.4.0
  cupertino_icons: ^1.0.5
  english_words: ^4.0.0
  country_code_picker: ^3.0.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_svg: ^2.0.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  global_configuration: ^2.0.0-nullsafety.1
  google_fonts: ^4.0.4
  image_network: ^2.5.1
  image_picker: ^0.8.4+4
  intl: ^0.18.1
  json_serializable: ^6.1.3
  mobile_scanner: ^3.2.0
  cached_network_image: ^3.2.3
  # modal_bottom_sheet: ^2.0.1
  pin_code_fields: ^7.4.0
  smooth_page_indicator: ^1.0.0+2
  sms_otp_auto_verify: ^2.1.0
  snippet_coder_utils: ^1.0.12
  flutter_swiper_plus: ^2.0.4
  go_router: ^7.1.1
  new_gradient_app_bar: ^0.2.0
  carousel_slider: ^4.2.1
  flutter_slidable: ^3.0.0
  google_maps_flutter: ^2.2.5
  shared_preferences: ^2.1.1
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^14.1.1
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter_native_splash: ^2.3.1
  # firebase_core: ^2.13.1
  # firebase_auth: ^4.6.2
  # firebase_database: ^10.2.2

dev_dependencies:
  
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.7
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/png/
    - assets/svg/
    - assets/image/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: poppins-regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
